name: Code Scan

on: [push]

jobs:
  scan:
    runs-on: [self-hosted, mule]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Scan RAML file
      run: |
        anypoint-cli governance profile list -o text
        anypoint-cli governance api validate --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/openapi-best-practices/1.0.0 /home/ubuntu/actions-runner/_work/salesforcetest/salesforcetest/demo
        echo "------------------------"
        anypoint-cli governance api validate --remote-rulesets 68ef9520-24e9-4cf2-b2f5-620025690913/authentication-security-best-practices/1.0.0,68ef9520-24e9-4cf2-b2f5-620025690913/openapi-best-practices/1.0.0 /home/ubuntu/actions-runner/_work/salesforcetest/salesforcetest/demo 
        
