name: Code Scan

on: [push]

jobs:
  scan:
    runs-on: [self-hosted, test, test2]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Scan RAML file
      run: |
        anypoint-cli governance profile create "profile 6" 68ef9520-24e9-4cf2-b2f5-620025690913/anypoint-best-practices/latest 68ef9520-24e9-4cf2-b2f5-620025690913/asyncapi-best-practices/latest 68ef9520-24e9-4cf2-b2f5-620025690913/authentication-security-best-practices/latest 68ef9520-24e9-4cf2-b2f5-620025690913/openapi-best-practices/latest 68ef9520-24e9-4cf2-b2f5-620025690913/required-examples/latest --criteria "tag:oas,category:API Type:Experience API,status:development,scope:rest-api" --description "test profile for Best Practices"
        anypoint-cli governance profile list -o text
        anypoint-cli governance profile info 3558a6d9-ffcd-466a-b5d0-1a593a17edc8 --output text
        anypoint-cli governance api validate .TestDetail.raml
        
