name: Code Scan

on: [push]


jobs:
  scan:
    runs-on: [self-hosted, test, ubuntu]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Set-up NodeJS version 16
      uses: actions/setup-node@v3
      with:
            node-version: 16

    - name: Install API Governance CLI
      run: |
        npm i -g anypoint-cli@latest
